theme: monophase

title: Mihailo Vojinović
email: mihailonvojinovic@gmail.com
url: "https://mihna123.github.io"
author_name: Mihailo Vojinović
description: Welcome to the my webpage! You can take a stay and have a look. If you want to get in touch, contact me via email.

disqus: mihna123s-personal-site
google_analytics: G-MVSJ60592C

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
